### ISSUE TITLE
Compatibility with Statamic 3.4

### ISSUE THREAD

**Issue by FlorianMoser** [jonassiewertsen/statamic-oh-dear#10]
Would it be possible to update the Composer dependencies to support Statamic 3.4?

**Comment by FlorianMoser** [comment]
I just tested the addon version 1.8.0 with Statamic 3.4.1 and it seems to work fine. So an update to `"statamic/cms": "3.0.* || 3.1.* || 3.2.* || 3.3.* || 3.4.*",` in composer.json should be enough.

**Comment by jonassiewertsen** [comment]
Sure. Feel always free to create a PR in the future.

**Comment by jonassiewertsen** [comment]
https://github.com/jonassiewertsen/statamic-oh-dear/releases/tag/v1.9.0

**Comment by FlorianMoser** [comment]
Perfect, thanks!

> Sure. Feel always free to create a PR in the future.

Will do so next time 👍
