### ISSUE TITLE
Can't install on Statamic 3.1.4

### ISSUE THREAD

**Issue by justinhough** [jonassiewertsen/statamic-oh-dear#5]
Was using this plugin in Statamic version 3.0, however, when I tried to update to the latest release it have an error about not being able to upgrade because of `statamic-oh-dear`. I removed it and upgraded the site, but it won't allow it to be installed with the Statamic version at 3.1.4.

Here is the error:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires jonassiewertsen/statamic-oh-dear ^1.4 -> satisfiable by jonassiewertsen/statamic-oh-dear[v1.4.0].
    - jonassiewertsen/statamic-oh-dear v1.4.0 requires statamic/cms 3.0.* -> found statamic/cms[v3.0.0-beta.1, ..., 3.0.x-dev] but it conflicts with your root composer.json require (3.1.4).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
````

**Comment by jonassiewertsen** [comment]
Hej Justin I haven't updated to Statamic 3.1 yet. 

I will do that soon, but am moving at the moment.

Feel free to create a PR here to add:
`3.0.* || 3.1.*`

https://github.com/jonassiewertsen/statamic-oh-dear/blob/master/composer.json#L28

A quick feedback if things are running smoothly would speed up the process. 
No worries! I would update soon, but you might be quicker then I am :-)

**Comment by justinhough** [comment]
@jonassiewertsen Created the pull request and checked through the changes on a local instance running Statamic 3. Didn't see any errors reported and looks to be running as it was before. Thanks.

**Comment by jonassiewertsen** [comment]
Thanks for checking @justinhough!

https://github.com/jonassiewertsen/statamic-oh-dear/releases/tag/v1.5.0
