### ISSUE TITLE
Add Laravel 9 support

### ISSUE THREAD

**Issue by jonassiewertsen** [jonassiewertsen/statamic-oh-dear#9]

**Comment by FlorianMoser** [comment]
Maybe it's enough to just bump the illuminate/support version?

```
"illuminate/support": "^7.0 || ^8.0 || ^9.0"
```

Because the addon currently can't be installed on current Statamic versions.

**Comment by jonassiewertsen** [comment]
That might be enough @FlorianMoser 

I am not using this addon activly at the moment.

Can you test if it works as expected?
I will happily create a new version if you can confirm that ☺️

**Comment by FlorianMoser** [comment]
Thanks, @jonassiewertsen 

I downloaded the addon and installed it as a local Composer package. It worked, as soon as I added
```
"illuminate/support": "^7.0 || ^8.0 || ^9.0"
```
to your composer.json file. I also checked the 5 pages plus the widget of the addon in the Statamic backend, and it all seems to work perfectly.

So a new release would be great 😎

**Comment by jonassiewertsen** [comment]
Thanks for testing. 

There you go: https://github.com/jonassiewertsen/statamic-oh-dear/releases/tag/v1.8.0

Let me know if something seems off.

**Comment by FlorianMoser** [comment]
I was just able to deploy the site successfully with the addon. Thanks, @jonassiewertsen !

**Comment by jonassiewertsen** [comment]
> I was just able to deploy the site successfully with the addon. Thanks, @jonassiewertsen !

Great to hear 🚀
